### ISSUE TITLE
Not Updating

### ISSUE THREAD

**Issue by gskarpelos** [FlyingDiver/Indigo-Trane-Nexia#11]
Wondering if there is an issue with the migration from the mynexia platform, to the tranehome platform. The plugin seemed to stop updating ( last read was end of June).

**Comment by JohnPolasek** [comment]
I have Just downloaded the plugin 8/6/21 after purchasing an 1050XL controlling an American Standard 4 zone variable speed and confirm the problem.  I have found that manually toggling the thermostat device from Fan Auto to Fan On and back again will cause the Indigo thermostat and zone devices to update.  However, this is not an automatable option in the Actions list for the plugin.  When I set an action in Indigo to change the Humidity set point in the thermostat device, I get a large number of error messages indicating the plugin is going into infinite recursion:

```
   Trane Nexia Error               Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 464, in setDehumidifySetpointAction
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_devices.py", line 109, in set_dehumidify_setpoint
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 879, in set_dehumidify_setpoint
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 172, in _put_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Many many repetitions
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 227, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 489, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 417, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/connectionpool.py", line 590, in urlopen
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/response.py", line 373, in from_httplib
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/_collections.py", line 324, in from_httplib
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/_collections.py", line 137, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 69, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 151, in __subclasscheck__
RuntimeError: maximum recursion depth exceeded

```

**Comment by welchgregusa** [comment]
I am also seeing the plugin seemingly not updating. It does update when I reload the plugin, but does not seem to after that, at least not reliably that I can tell. I'm trying to do some sleuthing...

**Comment by FlyingDiver** [comment]
Obsoleted by plugin rewrite. Open new issue if this reoccurs with 2022.1.0 or later.
