### ISSUE TITLE
Request connection error

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-Trane-Nexia#2]
User reported:

Trane Nexia Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
```
File "plugin.py", line 94, in runConcurrentThread
File "/Users/home/Documents/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_devices.py", line 61, in update
File "/Users/home/Documents/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 543, in get_thermostat_name
File "/Users/home/Documents/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 309, in _get_thermostat_key
File "/Users/home/Documents/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 272, in _get_thermostat_json
File "/Users/home/Documents/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 226, in _get_url
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 489, in get
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 467, in send
ConnectionError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

Trane Nexia Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```

**Comment by FlyingDiver** [comment]
Added check for request get failure.
