### ISSUE TITLE
v2022.1.0 error starting and stoping

### ISSUE THREAD

**Issue by akataz04** [FlyingDiver/Indigo-Trane-Nexia#21]
```
 Stopped plugin "Trane Home 2202.1.0"
   Starting plugin "Trane Home 2202.1.0" (pid 80223)
   Trane Home Debug                logLevel = 5
   Trane Home Debug                updateFrequency = 600.0
   Started plugin "Trane Home 2202.1.0"
   Trane Home Debug                startup
   Trane Home Debug                run_async_thread starting
   Trane Home Debug                startup complete
   Trane Home                      Trane Home User Account: Starting NexiaAccount Device 1058143417
   Trane Home                      Trane House Zone: Starting NexiaZone Device 1970472195
   Trane Home                      Trane Thermostat: Starting NexiaThermostat Device 1392576793
   Trane Home Debug                async_main: running
   Trane Home Debug                Trane Thermostat: starting update for thermostat 3351192
   Trane Home Debug                do_update: update_list: [{'key': 'thermostat_name', 'value': 'House'}, {'key': 'thermostat_model', 'value': 'XL950'}, {'key': 'thermostat_firmware', 'value': '4.0.3-CR11'}, {'key': 'thermostat_type', 'value': 'XL950'}, {'key': 'thermostat_id', 'value': '00422504'}, {'key': 'system_status', 'value': 'Cooling'}, {'key': 'fan_mode', 'value': 'Auto'}, {'key': 'has_variable_fan_speed', 'value': True}, {'key': 'fan_speed', 'value': 0.5}, {'key': 'has_relative_humidity', 'value': True}, {'key': 'relative_humidity', 'value': 0.58}, {'key': 'has_dehumidify_support', 'value': False}, {'key': 'dehumidify_setpoint', 'value': ''}, {'key': 'has_humidify_support', 'value': False}, {'key': 'humidify_setpoint', 'value': ''}, {'key': 'has_variable_speed_compressor', 'value': True}, {'key': 'compressor_speed_current', 'value': 0}, {'key': 'compressor_speed_requested', 'value': 0}, {'key': 'has_outdoor_temperature', 'value': True}, {'key': 'outdoor_temperature', 'value': 94.0}, {'key': 'has_emergency_heat', 'value': False}, {'key': 'is_emergency_heat_active', 'value': ''}, {'key': 'has_air_cleaner', 'value': True}, {'key': 'air_cleaner_mode', 'value': 'auto'}, {'key': 'is_blower_active', 'value': True}]
   Trane Home Debug                Trane House Zone: starting update for zone 3351192:0
   Trane Home Error                
Traceback (most recent call last):
  File "plugin.py", line 124, in run_async_thread
    self.event_loop.run_until_complete(self.async_main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "plugin.py", line 156, in async_main
    await self.do_update()
  File "plugin.py", line 217, in do_update
    zone = thermostat.get_zone_by_id(zone_id)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nexia/thermostat.py", line 568, in get_zone_by_id
    raise KeyError
KeyError
   Trane Home Debug                run_async_thread exiting
```

**Comment by FlyingDiver** [comment]
Use the "Write Nexia Data to Log" menu command and post that output.

**Comment by akataz04** [comment]
Trane Home                      
House:
```
{
    "_links": {
        "filter_events": {
            "href": "https://www.mynexia.com/mobile/houses/131100/events/collection?sys_guid=09766186-3e7d-4b56-b613-70b4f2f2d1d8"
        },
        "nexia:history": {
            "href": "https://www.mynexia.com/mobile/houses/131100/events?device_id=3351192"
        },
        "self": {
            "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192"
        }
    },
    "connected": true,
    "country_code": "US",
    "delta": 6,
    "features": [
        {
            "items": [
                {
                    "label": "Model",
                    "type": "label_value",
                    "value": "XL950"
                },
                {
                    "label": "AUID",
                    "type": "label_value",
                    "value": "00422504"
                },
                {
                    "label": "Firmware Build Number",
                    "type": "label_value",
                    "value": "1450083251"
                },
                {
                    "label": "Firmware Build Date",
                    "type": "label_value",
                    "value": "2015-12-14 08:54:11 UTC"
                },
                {
                    "label": "Firmware Version",
                    "type": "label_value",
                    "value": "4.0.3-CR11"
                }
            ],
            "name": "advanced_info"
        },
        {
            "actions": {
                "set_cool_setpoint": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/setpoints"
                }
            },
            "device_identifier": "XxlZone-84001381",
            "name": "thermostat",
            "operating_state": "cool",
            "scale": "f",
            "setpoint_cool": 75,
            "setpoint_cool_max": 99,
            "setpoint_cool_min": 60,
            "setpoint_delta": 6,
            "setpoint_heat_max": 90,
            "setpoint_heat_min": 55,
            "setpoint_increment": 1.0,
            "status": "Cooling",
            "status_icon": {
                "modifiers": [],
                "name": "cooling"
            },
            "system_status": "Cooling",
            "temperature": 76
        },
        {
            "is_connected": true,
            "name": "connection",
            "signal_strength": "unknown"
        },
        {
            "actions": {
                "request_current_dealer_info": {
                    "href": "https://www.mynexia.com/mobile/dealers/3055962666",
                    "method": "GET"
                },
                "request_dealers_by_zip": {
                    "href": "https://www.mynexia.com/mobile/dealers/3351192/search",
                    "method": "POST"
                }
            },
            "has_dealer_identifier": true,
            "name": "dealer_contact_info"
        },
        {
            "actions": {
                "update_thermostat_mode": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/zone_mode",
                    "method": "POST"
                }
            },
            "display_value": "Cooling",
            "label": "System Mode",
            "name": "thermostat_mode",
            "options": [
                {
                    "header": true,
                    "id": "thermostat_mode",
                    "label": "System Mode",
                    "value": "thermostat_mode"
                },
                {
                    "label": "Auto",
                    "value": "AUTO"
                },
                {
                    "label": "Cooling",
                    "value": "COOL"
                },
                {
                    "label": "Heating",
                    "value": "HEAT"
                },
                {
                    "label": "Off",
                    "value": "OFF"
                }
            ],
            "value": "COOL"
        },
        {
            "actions": {
                "update_thermostat_run_mode": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/run_mode",
                    "method": "POST"
                }
            },
            "display_value": "Hold",
            "label": "Run Mode",
            "name": "thermostat_run_mode",
            "options": [
                {
                    "header": true,
                    "id": "thermostat_run_mode",
                    "label": "Run Mode",
                    "value": "thermostat_run_mode"
                },
                {
                    "id": "info_text",
                    "info": true,
                    "label": "Follow or override the schedule.",
                    "value": "info_text"
                },
                {
                    "label": "Permanent Hold",
                    "value": "permanent_hold"
                },
                {
                    "label": "Run Schedule",
                    "value": "run_schedule"
                }
            ],
            "value": "permanent_hold"
        },
        {
            "actions": {
                "request_current_state": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/request_current_sensor_state"
                },
                "update_active_sensors": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/update_active_sensors",
                    "method": "POST"
                }
            },
            "name": "room_iq_sensors",
            "sensors": [
                {
                    "has_battery": false,
                    "has_online": false,
                    "humidity": 57,
                    "humidity_valid": true,
                    "icon": {
                        "modifiers": [],
                        "name": "room_iq_onboard"
                    },
                    "id": 16422076,
                    "name": "House",
                    "serial_number": "NativeIDTUniqueID",
                    "temperature": 76,
                    "temperature_valid": true,
                    "type": "thermostat",
                    "weight": 0.0
                }
            ],
            "should_show": false
        },
        {
            "actions": {
                "update_thermostat_fan_mode": {
                    "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192/fan_mode",
                    "method": "POST"
                }
            },
            "display_value": "Auto",
            "label": "Fan Mode",
            "name": "thermostat_fan_mode",
            "options": [
                {
                    "header": true,
                    "id": "thermostat_fan_mode",
                    "label": "Fan Mode",
                    "value": "thermostat_fan_mode"
                },
                {
                    "label": "Auto",
                    "value": "auto"
                },
                {
                    "label": "On",
                    "value": "on"
                },
                {
                    "label": "Circulate",
                    "value": "circulate"
                }
            ],
            "status_icon": {
                "modifiers": [],
                "name": "thermostat_fan_on"
            },
            "value": "auto"
        },
        {
            "actions": {
                "update_thermostat_default_fan_mode": {
                    "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192/default_fan_mode",
                    "method": "POST"
                }
            },
            "name": "thermostat_default_fan_mode",
            "value": "auto"
        },
        {
            "actions": {
                "enable_scheduling": {
                    "data": {
                        "value": true
                    },
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/scheduling_enabled",
                    "method": "POST"
                },
                "get_active_schedule": {
                    "href": "https://www.mynexia.com/mobile/thermostat_schedules/get_active_schedule?device_identifier=XxlThermostat-3351192",
                    "method": "POST"
                },
                "get_default_schedule": {
                    "href": "https://www.mynexia.com/mobile/thermostat_schedules/get_default_schedule?device_identifier=XxlThermostat-3351192",
                    "method": "GET"
                },
                "set_active_schedule": {
                    "href": "https://www.mynexia.com/mobile/thermostat_schedules/set_active_schedule?device_identifier=XxlThermostat-3351192",
                    "method": "POST"
                }
            },
            "can_add_remove_periods": true,
            "collection_url": "https://www.mynexia.com/mobile/schedules?device_identifier=XxlThermostat-3351192&house_id=131100",
            "enabled": true,
            "max_period_name_length": 10,
            "max_periods_per_day": 6,
            "name": "schedule",
            "setpoint_increment": 1.0
        }
    ],
    "generic_input_sensors": [],
    "has_indoor_humidity": true,
    "has_outdoor_temperature": true,
    "icon": [
        {
            "modifiers": [
                "temperature-76"
            ],
            "name": "thermostat"
        }
    ],
    "id": 3351192,
    "indoor_humidity": "58",
    "last_updated_at": "2023-07-31T17:55:02.000-04:00",
    "manufacturer": "Trane",
    "name": "House",
    "name_editable": true,
    "outdoor_temperature": "94",
    "settings": [
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/preset_selected"
                }
            },
            "current_value": 0,
            "labels": [
                "None",
                "Home",
                "Away",
                "Sleep"
            ],
            "options": [
                {
                    "label": "None",
                    "value": 0
                },
                {
                    "label": "Home",
                    "value": 1
                },
                {
                    "label": "Away",
                    "value": 2
                },
                {
                    "label": "Sleep",
                    "value": 3
                }
            ],
            "title": "Preset",
            "type": "preset_selected",
            "values": [
                0,
                1,
                2,
                3
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/zone_mode"
                }
            },
            "current_value": "COOL",
            "labels": [
                "Auto",
                "Cooling",
                "Heating",
                "Off"
            ],
            "options": [
                {
                    "label": "Auto",
                    "value": "AUTO"
                },
                {
                    "label": "Cooling",
                    "value": "COOL"
                },
                {
                    "label": "Heating",
                    "value": "HEAT"
                },
                {
                    "label": "Off",
                    "value": "OFF"
                }
            ],
            "title": "System Mode",
            "type": "system_mode",
            "values": [
                "AUTO",
                "COOL",
                "HEAT",
                "OFF"
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/run_mode"
                }
            },
            "current_value": "permanent_hold",
            "labels": [
                "Permanent Hold",
                "Run Schedule"
            ],
            "options": [
                {
                    "label": "Permanent Hold",
                    "value": "permanent_hold"
                },
                {
                    "label": "Run Schedule",
                    "value": "run_schedule"
                }
            ],
            "title": "Run Mode",
            "type": "run_mode",
            "values": [
                "permanent_hold",
                "run_schedule"
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/scheduling_enabled"
                }
            },
            "current_value": true,
            "labels": [
                "ON",
                "OFF"
            ],
            "options": [
                {
                    "label": "ON",
                    "value": true
                },
                {
                    "label": "OFF",
                    "value": false
                }
            ],
            "title": "Scheduling",
            "type": "scheduling_enabled",
            "values": [
                true,
                false
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192/fan_mode"
                }
            },
            "current_value": "auto",
            "labels": [
                "Auto",
                "On",
                "Circulate"
            ],
            "options": [
                {
                    "label": "Auto",
                    "value": "auto"
                },
                {
                    "label": "On",
                    "value": "on"
                },
                {
                    "label": "Circulate",
                    "value": "circulate"
                }
            ],
            "title": "Fan Mode",
            "type": "fan_mode",
            "values": [
                "auto",
                "on",
                "circulate"
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192/fan_speed"
                }
            },
            "current_value": 0.5,
            "labels": [
                "35%",
                "40%",
                "45%",
                "50%",
                "55%",
                "60%",
                "65%",
                "70%",
                "75%",
                "80%",
                "85%",
                "90%",
                "95%",
                "100%"
            ],
            "options": [
                {
                    "label": "35%",
                    "value": 0.35
                },
                {
                    "label": "40%",
                    "value": 0.4
                },
                {
                    "label": "45%",
                    "value": 0.45
                },
                {
                    "label": "50%",
                    "value": 0.5
                },
                {
                    "label": "55%",
                    "value": 0.55
                },
                {
                    "label": "60%",
                    "value": 0.6
                },
                {
                    "label": "65%",
                    "value": 0.65
                },
                {
                    "label": "70%",
                    "value": 0.7
                },
                {
                    "label": "75%",
                    "value": 0.75
                },
                {
                    "label": "80%",
                    "value": 0.8
                },
                {
                    "label": "85%",
                    "value": 0.85
                },
                {
                    "label": "90%",
                    "value": 0.9
                },
                {
                    "label": "95%",
                    "value": 0.95
                },
                {
                    "label": "100%",
                    "value": 1.0
                }
            ],
            "title": "Fan Speed",
            "type": "fan_speed",
            "values": [
                0.35,
                0.4,
                0.45,
                0.5,
                0.55,
                0.6,
                0.65,
                0.7,
                0.75,
                0.8,
                0.85,
                0.9,
                0.95,
                1.0
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192/fan_circulation_time"
                }
            },
            "current_value": 20,
            "labels": [
                "10 minutes",
                "15 minutes",
                "20 minutes",
                "25 minutes",
                "30 minutes",
                "35 minutes",
                "40 minutes",
                "45 minutes",
                "50 minutes",
                "55 minutes"
            ],
            "options": [
                {
                    "label": "10 minutes",
                    "value": 10
                },
                {
                    "label": "15 minutes",
                    "value": 15
                },
                {
                    "label": "20 minutes",
                    "value": 20
                },
                {
                    "label": "25 minutes",
                    "value": 25
                },
                {
                    "label": "30 minutes",
                    "value": 30
                },
                {
                    "label": "35 minutes",
                    "value": 35
                },
                {
                    "label": "40 minutes",
                    "value": 40
                },
                {
                    "label": "45 minutes",
                    "value": 45
                },
                {
                    "label": "50 minutes",
                    "value": 50
                },
                {
                    "label": "55 minutes",
                    "value": 55
                }
            ],
            "title": "Fan Circulation Time",
            "type": "fan_circulation_time",
            "values": [
                10,
                15,
                20,
                25,
                30,
                35,
                40,
                45,
                50,
                55
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192/air_cleaner_mode"
                }
            },
            "current_value": "auto",
            "labels": [
                "Auto",
                "Quick",
                "Allergy"
            ],
            "options": [
                {
                    "label": "Auto",
                    "value": "auto"
                },
                {
                    "label": "Quick",
                    "value": "quick"
                },
                {
                    "label": "Allergy",
                    "value": "allergy"
                }
            ],
            "title": "Air Cleaner Mode",
            "type": "air_cleaner_mode",
            "values": [
                "auto",
                "quick",
                "allergy"
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192/scale"
                }
            },
            "current_value": "f",
            "labels": [
                "F",
                "C"
            ],
            "options": [
                {
                    "label": "F",
                    "value": "f"
                },
                {
                    "label": "C",
                    "value": "c"
                }
            ],
            "title": "Temperature Scale",
            "type": "scale",
            "values": [
                "f",
                "c"
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192/filter_reminders_enabled"
                }
            },
            "current_value": false,
            "labels": [
                "On",
                "Off"
            ],
            "options": [
                {
                    "label": "On",
                    "value": true
                },
                {
                    "label": "Off",
                    "value": false
                }
            ],
            "title": "Send Filter Reminders",
            "type": "filter_reminders_enabled",
            "values": [
                true,
                false
            ]
        },
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_thermostats/3351192/filter_size"
                }
            },
            "current_value": null,
            "labels": [
                "14x14x1",
                "14x20x1",
                "14x25x1",
                "16x16x1",
                "16x20x1",
                "16x25x1",
                "20x20x1",
                "20x22x1",
                "20x25x1",
                "20x30x1"
            ],
            "options": [
                {
                    "label": "14x14x1",
                    "value": "14x14x1"
                },
                {
                    "label": "14x20x1",
                    "value": "14x20x1"
                },
                {
                    "label": "14x25x1",
                    "value": "14x25x1"
                },
                {
                    "label": "16x16x1",
                    "value": "16x16x1"
                },
                {
                    "label": "16x20x1",
                    "value": "16x20x1"
                },
                {
                    "label": "16x25x1",
                    "value": "16x25x1"
                },
                {
                    "label": "20x20x1",
                    "value": "20x20x1"
                },
                {
                    "label": "20x22x1",
                    "value": "20x22x1"
                },
                {
                    "label": "20x25x1",
                    "value": "20x25x1"
                },
                {
                    "label": "20x30x1",
                    "value": "20x30x1"
                }
            ],
            "title": "Filter Size",
            "type": "filter_size",
            "values": [
                "14x14x1",
                "14x20x1",
                "14x25x1",
                "16x16x1",
                "16x20x1",
                "16x25x1",
                "20x20x1",
                "20x22x1",
                "20x25x1",
                "20x30x1"
            ]
        }
    ],
    "state_code": "FL",
    "status_secondary": null,
    "status_tertiary": null,
    "system_status": "Cooling",
    "type": "xxl_thermostat",
    "zones": [
        {
            "_links": {
                "self": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381"
                }
            },
            "cooling_setpoint": 75,
            "current_zone_mode": "COOL",
            "features": [
                {
                    "actions": {
                        "set_cool_setpoint": {
                            "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/setpoints"
                        }
                    },
                    "device_identifier": "XxlZone-84001381",
                    "name": "thermostat",
                    "scale": "f",
                    "setpoint_cool": 75,
                    "setpoint_cool_max": 99,
                    "setpoint_cool_min": 60,
                    "setpoint_delta": 6,
                    "setpoint_heat_max": 90,
                    "setpoint_heat_min": 55,
                    "setpoint_increment": 1.0,
                    "status": "",
                    "status_icon": {
                        "modifiers": [],
                        "name": "cooling"
                    },
                    "system_status": "Cooling",
                    "temperature": 76
                },
                {
                    "is_connected": true,
                    "name": "connection",
                    "signal_strength": "unknown"
                },
                {
                    "actions": {
                        "request_current_dealer_info": {
                            "href": "https://www.mynexia.com/mobile/dealers/3055962666",
                            "method": "GET"
                        },
                        "request_dealers_by_zip": {
                            "href": "https://www.mynexia.com/mobile/dealers/3351192/search",
                            "method": "POST"
                        }
                    },
                    "has_dealer_identifier": true,
                    "name": "dealer_contact_info"
                },
                {
                    "actions": {
                        "update_thermostat_mode": {
                            "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/zone_mode",
                            "method": "POST"
                        }
                    },
                    "display_value": "Cooling",
                    "label": "System Mode",
                    "name": "thermostat_mode",
                    "options": [
                        {
                            "header": true,
                            "id": "thermostat_mode",
                            "label": "System Mode",
                            "value": "thermostat_mode"
                        },
                        {
                            "label": "Auto",
                            "value": "AUTO"
                        },
                        {
                            "label": "Cooling",
                            "value": "COOL"
                        },
                        {
                            "label": "Heating",
                            "value": "HEAT"
                        },
                        {
                            "label": "Off",
                            "value": "OFF"
                        }
                    ],
                    "value": "COOL"
                },
                {
                    "actions": {
                        "update_thermostat_run_mode": {
                            "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/run_mode",
                            "method": "POST"
                        }
                    },
                    "display_value": "Hold",
                    "label": "Run Mode",
                    "name": "thermostat_run_mode",
                    "options": [
                        {
                            "header": true,
                            "id": "thermostat_run_mode",
                            "label": "Run Mode",
                            "value": "thermostat_run_mode"
                        },
                        {
                            "id": "info_text",
                            "info": true,
                            "label": "Follow or override the schedule.",
                            "value": "info_text"
                        },
                        {
                            "label": "Permanent Hold",
                            "value": "permanent_hold"
                        },
                        {
                            "label": "Run Schedule",
                            "value": "run_schedule"
                        }
                    ],
                    "value": "permanent_hold"
                },
                {
                    "actions": {
                        "request_current_state": {
                            "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/request_current_sensor_state"
                        },
                        "update_active_sensors": {
                            "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/update_active_sensors",
                            "method": "POST"
                        }
                    },
                    "name": "room_iq_sensors",
                    "sensors": [
                        {
                            "has_battery": false,
                            "has_online": false,
                            "humidity": 57,
                            "humidity_valid": true,
                            "icon": {
                                "modifiers": [],
                                "name": "room_iq_onboard"
                            },
                            "id": 16422076,
                            "name": "House",
                            "serial_number": "NativeIDTUniqueID",
                            "temperature": 76,
                            "temperature_valid": true,
                            "type": "thermostat",
                            "weight": 0.0
                        }
                    ],
                    "should_show": false
                },
                {
                    "actions": {
                        "enable_scheduling": {
                            "data": {
                                "value": true
                            },
                            "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/scheduling_enabled",
                            "method": "POST"
                        },
                        "get_active_schedule": {
                            "href": "https://www.mynexia.com/mobile/thermostat_schedules/get_active_schedule?device_identifier=XxlZone-84001381",
                            "method": "POST"
                        },
                        "get_default_schedule": {
                            "href": "https://www.mynexia.com/mobile/thermostat_schedules/get_default_schedule?device_identifier=XxlZone-84001381",
                            "method": "GET"
                        },
                        "set_active_schedule": {
                            "href": "https://www.mynexia.com/mobile/thermostat_schedules/set_active_schedule?device_identifier=XxlZone-84001381",
                            "method": "POST"
                        }
                    },
                    "can_add_remove_periods": true,
                    "collection_url": "https://www.mynexia.com/mobile/schedules?device_identifier=XxlZone-84001381&house_id=131100",
                    "enabled": true,
                    "max_period_name_length": 10,
                    "max_periods_per_day": 6,
                    "name": "schedule",
                    "setpoint_increment": 1.0
                }
            ],
            "heating_setpoint": null,
            "icon": {
                "modifiers": [
                    "temperature-76"
                ],
                "name": "thermostat"
            },
            "id": 84001381,
            "name": "NativeZone",
            "operating_state": "",
            "setpoints": {
                "cool": 75,
                "heat": null
            },
            "settings": [],
            "temperature": 76,
            "type": "xxl_zone",
            "zone_status": ""
        }
    ]
}
```
   Trane Home                      
House NativeZone:
```
{
    "_links": {
        "self": {
            "href": "https://www.mynexia.com/mobile/xxl_zones/84001381"
        }
    },
    "cooling_setpoint": 75,
    "current_zone_mode": "COOL",
    "features": [
        {
            "actions": {
                "set_cool_setpoint": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/setpoints"
                }
            },
            "device_identifier": "XxlZone-84001381",
            "name": "thermostat",
            "scale": "f",
            "setpoint_cool": 75,
            "setpoint_cool_max": 99,
            "setpoint_cool_min": 60,
            "setpoint_delta": 6,
            "setpoint_heat_max": 90,
            "setpoint_heat_min": 55,
            "setpoint_increment": 1.0,
            "status": "",
            "status_icon": {
                "modifiers": [],
                "name": "cooling"
            },
            "system_status": "Cooling",
            "temperature": 76
        },
        {
            "is_connected": true,
            "name": "connection",
            "signal_strength": "unknown"
        },
        {
            "actions": {
                "request_current_dealer_info": {
                    "href": "https://www.mynexia.com/mobile/dealers/3055962666",
                    "method": "GET"
                },
                "request_dealers_by_zip": {
                    "href": "https://www.mynexia.com/mobile/dealers/3351192/search",
                    "method": "POST"
                }
            },
            "has_dealer_identifier": true,
            "name": "dealer_contact_info"
        },
        {
            "actions": {
                "update_thermostat_mode": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/zone_mode",
                    "method": "POST"
                }
            },
            "display_value": "Cooling",
            "label": "System Mode",
            "name": "thermostat_mode",
            "options": [
                {
                    "header": true,
                    "id": "thermostat_mode",
                    "label": "System Mode",
                    "value": "thermostat_mode"
                },
                {
                    "label": "Auto",
                    "value": "AUTO"
                },
                {
                    "label": "Cooling",
                    "value": "COOL"
                },
                {
                    "label": "Heating",
                    "value": "HEAT"
                },
                {
                    "label": "Off",
                    "value": "OFF"
                }
            ],
            "value": "COOL"
        },
        {
            "actions": {
                "update_thermostat_run_mode": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/run_mode",
                    "method": "POST"
                }
            },
            "display_value": "Hold",
            "label": "Run Mode",
            "name": "thermostat_run_mode",
            "options": [
                {
                    "header": true,
                    "id": "thermostat_run_mode",
                    "label": "Run Mode",
                    "value": "thermostat_run_mode"
                },
                {
                    "id": "info_text",
                    "info": true,
                    "label": "Follow or override the schedule.",
                    "value": "info_text"
                },
                {
                    "label": "Permanent Hold",
                    "value": "permanent_hold"
                },
                {
                    "label": "Run Schedule",
                    "value": "run_schedule"
                }
            ],
            "value": "permanent_hold"
        },
        {
            "actions": {
                "request_current_state": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/request_current_sensor_state"
                },
                "update_active_sensors": {
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/update_active_sensors",
                    "method": "POST"
                }
            },
            "name": "room_iq_sensors",
            "sensors": [
                {
                    "has_battery": false,
                    "has_online": false,
                    "humidity": 57,
                    "humidity_valid": true,
                    "icon": {
                        "modifiers": [],
                        "name": "room_iq_onboard"
                    },
                    "id": 16422076,
                    "name": "House",
                    "serial_number": "NativeIDTUniqueID",
                    "temperature": 76,
                    "temperature_valid": true,
                    "type": "thermostat",
                    "weight": 0.0
                }
            ],
            "should_show": false
        },
        {
            "actions": {
                "enable_scheduling": {
                    "data": {
                        "value": true
                    },
                    "href": "https://www.mynexia.com/mobile/xxl_zones/84001381/scheduling_enabled",
                    "method": "POST"
                },
                "get_active_schedule": {
                    "href": "https://www.mynexia.com/mobile/thermostat_schedules/get_active_schedule?device_identifier=XxlZone-84001381",
                    "method": "POST"
                },
                "get_default_schedule": {
                    "href": "https://www.mynexia.com/mobile/thermostat_schedules/get_default_schedule?device_identifier=XxlZone-84001381",
                    "method": "GET"
                },
                "set_active_schedule": {
                    "href": "https://www.mynexia.com/mobile/thermostat_schedules/set_active_schedule?device_identifier=XxlZone-84001381",
                    "method": "POST"
                }
            },
            "can_add_remove_periods": true,
            "collection_url": "https://www.mynexia.com/mobile/schedules?device_identifier=XxlZone-84001381&house_id=131100",
            "enabled": true,
            "max_period_name_length": 10,
            "max_periods_per_day": 6,
            "name": "schedule",
            "setpoint_increment": 1.0
        }
    ],
    "heating_setpoint": null,
    "icon": {
        "modifiers": [
            "temperature-76"
        ],
        "name": "thermostat"
    },
    "id": 84001381,
    "name": "NativeZone",
    "operating_state": "",
    "setpoints": {
        "cool": 75,
        "heat": null
    },
    "settings": [],
    "temperature": 76,
    "type": "xxl_zone",
    "zone_status": ""
}
```

**Comment by FlyingDiver** [comment]
Ah.  The API changed the way zones are identified recently.  Edit both your thermostat and zone devices.  Just open then save.  See if the address field for the zone changes.

**Comment by akataz04** [comment]
Problem closed!

**Comment by FlyingDiver** [comment]
I need to add that to the instructions.
