### ISSUE TITLE
Error authenticating on temp change

### ISSUE THREAD

**Issue by johnsturgeon** [FlyingDiver/Indigo-Trane-Nexia#4]
I'm getting the following error when trying to change the temp on my thermostate
```
Traceback (most recent call last):
  File "plugin.py", line 384, in actionControlThermostat
  File "plugin.py", line 407, in handleChangeSetpointAction
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_devices.py", line 234, in set_zone_heat_cool_temp
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 1316, in set_zone_heat_cool_temp
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 172, in _put_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
```

The temperature reads fine, it shows the current temp correctly, but this just happens whenever I try and change it.

**Comment by FlyingDiver** [comment]
I don't see the actual error message before the traceback.  Please enable debug level logging and repeat the operation, and include the previous log output.  Also, include the output from the "Write Thermostat Data to Log" plugin menu command.

**Comment by johnsturgeon** [comment]
Thanks for such a quick reply, before seeing it, I completely removed and re-installed the plugin, and now it works.  It seems somehow that the 'thermostat' setting of the zone is getting confused sometimes

It is working now, but the zone settings still show the wrong thermostat:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/9746310/98557954-b8098f00-2259-11eb-99f1-d82be58affd8.png">

It should be `Trane Nexia Thermostat`
<img width="178" alt="image" src="https://user-images.githubusercontent.com/9746310/98558164-f1da9580-2259-11eb-99f8-495646e6d5cf.png">

**Comment by FlyingDiver** [comment]
Yeah, that's issue #3.  I'll fix it eventually.

**Comment by johnsturgeon** [comment]
I think I want to re-open this...

I just added an automation for turning on the 'air clean' mode, and it gives me the error that I showed above, here's the entire stack:
```
   Trane Nexia Error               Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 459, in setAirCleanerModeAction
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_devices.py", line 106, in set_air_cleaner
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 827, in set_air_cleaner
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 172, in _put_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url




AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 227, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 489, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 417, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/connectionpool.py", line 590, in urlopen
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/response.py", line 373, in from_httplib
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/_collections.py", line 324, in from_httplib
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/_collections.py", line 137, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 69, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 151, in __subclasscheck__
RuntimeError: maximum recursion depth exceeded
```

Seems to be a recursion issue

**Comment by FlyingDiver** [comment]
Yeah, that's an entirely different issue.  I'll need to track that one down.

**Comment by FlyingDiver** [comment]
First thing you need to do is get rid of the duplicate plugin (if you have one) and rename it to the original name.  Any followup on this problem will be in the new issue.

"Trane Nexia 6.27.07 AM.indigoPlugin"

**Comment by johnsturgeon** [comment]
Ah!  Yep.. Will do.  thanks

**Comment by FlyingDiver** [comment]
John - please see issue #5 - are you able to replicate the issue after fixing the duplicate plugin?  Please reply on that issue, not here.
