### ISSUE TITLE
Recursion in setAirCleanerModeAction

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-Trane-Nexia#5]
I think I want to re-open this...

I just added an automation for turning on the 'air clean' mode, and it gives me the error that I showed above, here's the entire stack:
```
   Trane Nexia Error               Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 459, in setAirCleanerModeAction
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_devices.py", line 106, in set_air_cleaner
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 827, in set_air_cleaner
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 172, in _put_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url



  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Trane Nexia 6.27.07 AM.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 227, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 489, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 417, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/connectionpool.py", line 590, in urlopen
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/response.py", line 373, in from_httplib
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/_collections.py", line 324, in from_httplib
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/_collections.py", line 137, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 69, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 151, in __subclasscheck__
RuntimeError: maximum recursion depth exceeded
```

Seems to be a recursion issue

_Originally posted by @johnsturgeon in https://github.com/FlyingDiver/Indigo-Trane-Nexia/issues/4#issuecomment-724099159_

**Comment by FlyingDiver** [comment]
The authentication process for this reverse-engineered API is wonky.

**Comment by FlyingDiver** [comment]
This is probably the same root cause as #7.

**Comment by FlyingDiver** [comment]
Obsoleted by plugin rewrite. Open new issue if this reoccurs with 2022.1.0 or later.
