### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by johnsturgeon** [FlyingDiver/Indigo-Trane-Nexia#7]
I'm still getting this error
```
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
```
(repeats 100s of times in the log)
Roughly once / day, the thermostat becomes unresponsive in Indigo (just leaves it at the 'last' temp, doesn't update)

**Comment by FlyingDiver** [comment]
That looks like a partial entry.  It doesn't have the actual error message.

**Comment by johnsturgeon** [comment]
sorry, here's the whole thing (minus the 880 lines of repeated errors)
```
Feb 1, 2021 at 5:31:55 AM
   Trane Nexia Error               Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 347, in actionControlThermostat
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_devices.py", line 230, in set_zone_mode
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 1365, in set_zone_mode
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 172, in _put_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 234, in _get_url
  ...
  [repeated 100s of times]
  ...
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 394, in login
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 129, in _get_authenticity_token
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 227, in _get_url
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 489, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 417, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/connectionpool.py", line 590, in urlopen
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/response.py", line 373, in from_httplib
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/_collections.py", line 324, in from_httplib
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/packages/urllib3/_collections.py", line 137, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 69, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 151, in __subclasscheck__
RuntimeError: maximum recursion depth exceeded
```

**Comment by FlyingDiver** [comment]
Do you get that error when sending a command after it's become unresponsive?

**Comment by FlyingDiver** [comment]
Obsoleted by plugin rewrite. Open new issue if this reoccurs with 2022.1.0 or later.
